# Generated by Django 4.1.2 on 2022-11-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='none', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
