# Generated by Django 4.1.2 on 2022-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantReviews', '0002_alter_review_restaurant_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
