# Generated by Django 4.1.2 on 2022-11-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantReviews', '0002_restaurant_state_alter_restaurant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
