# Generated by Django 4.1.2 on 2022-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantReviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='street_address',
            field=models.CharField(max_length=40),
        ),
    ]
